/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package elementosmixtos;

import java.awt.Color;
import java.lang.foreign.MemoryLayout;
import javax.swing.ButtonGroup;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author galog
 */
public class Elementos_Mixtos extends javax.swing.JFrame {

    /**
     * Creates new form Elementos_Mixtos
     */
    public Elementos_Mixtos() {
        initComponents();

        setTitle("GUI mixta");
        setResizable(false);
        tickVerde.setVisible(false);
        ButtonGroup group = new ButtonGroup();
        ButtonGroup groupE = new ButtonGroup();
        group.add(RadioBoton1);
        group.add(RadioBoton2);
        group.add(RadioBoton3);
        groupE.add(RadioBoton1E);
        groupE.add(RadioBoton2E);
        groupE.add(RadioBoton3E);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RadioBoton1 = new javax.swing.JRadioButton();
        RadioBoton2 = new javax.swing.JRadioButton();
        RadioBoton3 = new javax.swing.JRadioButton();
        CheckBox1 = new javax.swing.JCheckBox();
        CheckBox2 = new javax.swing.JCheckBox();
        CheckBox3 = new javax.swing.JCheckBox();
        CampoSimple = new javax.swing.JTextField();
        CampoCorreo = new javax.swing.JTextField();
        TextoCorreo = new javax.swing.JLabel();
        ComboBoxItems = new javax.swing.JComboBox<>();
        BarraHorizontal = new javax.swing.JSlider();
        Contador = new javax.swing.JSpinner();
        BotonEstado = new javax.swing.JToggleButton();
        RadioBoton1E = new javax.swing.JRadioButton();
        RadioBoton2E = new javax.swing.JRadioButton();
        RadioBoton3E = new javax.swing.JRadioButton();
        CheckBox1E = new javax.swing.JCheckBox();
        CheckBox2E = new javax.swing.JCheckBox();
        CheckBox3E = new javax.swing.JCheckBox();
        CampoSimpleE = new javax.swing.JTextField();
        TextoCorreoE = new javax.swing.JLabel();
        CampoCorreoE = new javax.swing.JTextField();
        ContadorE = new javax.swing.JSpinner();
        ComboBoxItemsE = new javax.swing.JComboBox<>();
        BotonEstadoE = new javax.swing.JToggleButton();
        BarraHorizontalE = new javax.swing.JSlider();
        BarraEstado = new javax.swing.JProgressBar();
        tickVerde = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GUI mixtsa");
        setResizable(false);

        RadioBoton1.setText("Opcion 1");
        RadioBoton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RadioBoton1MouseClicked(evt);
            }
        });

        RadioBoton2.setText("Opcion 2");
        RadioBoton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RadioBoton2MouseClicked(evt);
            }
        });

        RadioBoton3.setText("Opcion 3");
        RadioBoton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RadioBoton3MouseClicked(evt);
            }
        });

        CheckBox1.setText("Opcion 4");
        CheckBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CheckBox1MouseClicked(evt);
            }
        });

        CheckBox2.setText("Opcion 5");
        CheckBox2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CheckBox2MouseClicked(evt);
            }
        });

        CheckBox3.setText("Opcion 5");
        CheckBox3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CheckBox3MouseClicked(evt);
            }
        });

        CampoSimple.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CampoSimpleKeyReleased(evt);
            }
        });

        CampoCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CampoCorreoKeyReleased(evt);
            }
        });

        TextoCorreo.setText("Correo");

        ComboBoxItems.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboBoxItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxItemsActionPerformed(evt);
            }
        });

        BarraHorizontal.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                BarraHorizontalMouseDragged(evt);
            }
        });

        Contador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ContadorMouseClicked(evt);
            }
        });

        BotonEstado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elementosmixtos/b_off.png"))); // NOI18N
        BotonEstado.setRolloverEnabled(false);
        BotonEstado.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/elementosmixtos/b_on.png"))); // NOI18N
        BotonEstado.setVerifyInputWhenFocusTarget(false);
        BotonEstado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonEstadoMouseClicked(evt);
            }
        });

        RadioBoton1E.setText("Opcion 1");
        RadioBoton1E.setEnabled(false);

        RadioBoton2E.setText("Opcion 2");
        RadioBoton2E.setEnabled(false);

        RadioBoton3E.setText("Opcion 3");
        RadioBoton3E.setEnabled(false);

        CheckBox1E.setText("Opcion 4");
        CheckBox1E.setEnabled(false);

        CheckBox2E.setText("Opcion 5");
        CheckBox2E.setEnabled(false);

        CheckBox3E.setText("Opcion 6");
        CheckBox3E.setEnabled(false);

        CampoSimpleE.setEnabled(false);
        CampoSimpleE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoSimpleEActionPerformed(evt);
            }
        });

        TextoCorreoE.setText("Correo");
        TextoCorreoE.setEnabled(false);

        CampoCorreoE.setEnabled(false);

        ContadorE.setEnabled(false);

        ComboBoxItemsE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboBoxItemsE.setEnabled(false);

        BotonEstadoE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elementosmixtos/b_off.png"))); // NOI18N
        BotonEstadoE.setEnabled(false);
        BotonEstadoE.setRolloverEnabled(false);
        BotonEstadoE.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/elementosmixtos/b_on.png"))); // NOI18N

        BarraHorizontalE.setEnabled(false);

        tickVerde.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elementosmixtos/tick.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(RadioBoton3E)
                                .addGap(18, 18, 18)
                                .addComponent(CheckBox3E))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(RadioBoton1E)
                                .addGap(29, 29, 29)
                                .addComponent(CheckBox1E)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(BotonEstadoE)
                                .addGap(83, 83, 83))
                            .addComponent(BarraHorizontalE, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(RadioBoton2E)
                        .addGap(18, 18, 18)
                        .addComponent(CheckBox2E)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RadioBoton1)
                            .addComponent(RadioBoton2)
                            .addComponent(RadioBoton3)
                            .addComponent(TextoCorreo))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CampoCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(tickVerde)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(CheckBox2)
                                    .addComponent(CheckBox1)
                                    .addComponent(CheckBox3))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(ComboBoxItems, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(Contador))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(BotonEstado)
                                        .addGap(52, 52, 52))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(CampoSimple, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(ContadorE, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(CampoSimpleE, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(ComboBoxItemsE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                                        .addComponent(BarraHorizontal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(29, 29, 29))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(TextoCorreoE)
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BarraEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CampoCorreoE, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RadioBoton1)
                            .addComponent(CheckBox1)
                            .addComponent(CampoSimple, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BarraHorizontal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RadioBoton2)
                            .addComponent(CheckBox2)
                            .addComponent(Contador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(RadioBoton3)
                                    .addComponent(CheckBox3)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(ComboBoxItems, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(BotonEstado)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CampoCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextoCorreo)
                    .addComponent(tickVerde))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RadioBoton1E)
                            .addComponent(CheckBox1E))
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CampoSimpleE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BarraHorizontalE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RadioBoton2E)
                            .addComponent(CheckBox2E)
                            .addComponent(ContadorE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 94, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(RadioBoton3E)
                                    .addComponent(CheckBox3E)
                                    .addComponent(ComboBoxItemsE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(46, 46, 46))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(BotonEstadoE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CampoCorreoE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextoCorreoE))
                        .addGap(29, 29, 29)))
                .addComponent(BarraEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CampoSimpleEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoSimpleEActionPerformed
        //NO SIRVE ESTE EVENTO

    }//GEN-LAST:event_CampoSimpleEActionPerformed

    private void RadioBoton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RadioBoton1MouseClicked
        if (RadioBoton1.isSelected() == true) {
            RadioBoton1E.setSelected(true);
        }

        if (RadioBoton1.isSelected() == false) {
            RadioBoton1E.setSelected(false);
        }


    }//GEN-LAST:event_RadioBoton1MouseClicked

    private void RadioBoton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RadioBoton2MouseClicked
        if (RadioBoton2.isSelected() == true) {
            RadioBoton2E.setSelected(true);
        }

        if (RadioBoton2.isSelected() == false) {
            RadioBoton2E.setSelected(false);
        }
    }//GEN-LAST:event_RadioBoton2MouseClicked

    private void RadioBoton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RadioBoton3MouseClicked
        if (RadioBoton3.isSelected() == true) {
            RadioBoton3E.setSelected(true);
        }

        if (RadioBoton3.isSelected() == false) {
            RadioBoton3E.setSelected(false);
        }
    }//GEN-LAST:event_RadioBoton3MouseClicked

    private void CheckBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CheckBox1MouseClicked
        if (CheckBox1.isSelected() == true) {
            CheckBox1E.setSelected(true);
        }

        if (CheckBox1.isSelected() == false) {
            CheckBox1E.setSelected(false);
        }
    }//GEN-LAST:event_CheckBox1MouseClicked

    private void CheckBox2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CheckBox2MouseClicked
        if (CheckBox2.isSelected() == true) {
            CheckBox2E.setSelected(true);
        }

        if (CheckBox2.isSelected() == false) {
            CheckBox2E.setSelected(false);
        }
    }//GEN-LAST:event_CheckBox2MouseClicked

    private void CheckBox3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CheckBox3MouseClicked
        if (CheckBox3.isSelected() == true) {
            CheckBox3E.setSelected(true);
        }

        if (CheckBox3.isSelected() == false) {
            CheckBox3E.setSelected(false);
        }
    }//GEN-LAST:event_CheckBox3MouseClicked

    private void BotonEstadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonEstadoMouseClicked
        if (BotonEstado.isSelected() == true) {
            BotonEstadoE.setSelected(true);
        }

        if (BotonEstado.isSelected() == false) {
            BotonEstadoE.setSelected(false);
        }
    }//GEN-LAST:event_BotonEstadoMouseClicked

    private void ComboBoxItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxItemsActionPerformed
        ComboBoxItemsE.setSelectedIndex(ComboBoxItems.getSelectedIndex());
    }//GEN-LAST:event_ComboBoxItemsActionPerformed

    private void ContadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ContadorMouseClicked
        Contador.addChangeListener(new ChangeListener(){
            
            
           public void stateChanged (ChangeEvent e){
               
               int value = (int) Contador.getValue();
               ContadorE.setValue(value);
               
           } 
            
        });
    }//GEN-LAST:event_ContadorMouseClicked

    private void BarraHorizontalMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraHorizontalMouseDragged
        BarraHorizontalE.setValue(BarraHorizontal.getValue());
    }//GEN-LAST:event_BarraHorizontalMouseDragged

    private void CampoSimpleKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CampoSimpleKeyReleased
        CampoSimpleE.setText(CampoSimple.getText());
    }//GEN-LAST:event_CampoSimpleKeyReleased

    private void CampoCorreoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CampoCorreoKeyReleased
         CampoCorreoE.setText(CampoCorreo.getText());
        if (!CampoCorreo.getText().contains("@") || !CampoCorreo.getText().contains(".")){
            CampoCorreo.setBorder(javax.swing.BorderFactory.createLineBorder(Color.RED));
            
            BarraEstado.setBorder(javax.swing.BorderFactory.createLineBorder(Color.RED));
            tickVerde.setVisible(false);
        }
        
        if (CampoCorreo.getText().contains("@") && CampoCorreo.getText().contains(".")){
            CampoCorreo.setBorder(javax.swing.BorderFactory.createLineBorder(Color.GREEN));
            
            BarraEstado.setBorder(javax.swing.BorderFactory.createLineBorder(Color.green));
            tickVerde.setVisible(true);
       }
    }//GEN-LAST:event_CampoCorreoKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Elementos_Mixtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Elementos_Mixtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Elementos_Mixtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Elementos_Mixtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Elementos_Mixtos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar BarraEstado;
    private javax.swing.JSlider BarraHorizontal;
    private javax.swing.JSlider BarraHorizontalE;
    private javax.swing.JToggleButton BotonEstado;
    private javax.swing.JToggleButton BotonEstadoE;
    private javax.swing.JTextField CampoCorreo;
    private javax.swing.JTextField CampoCorreoE;
    private javax.swing.JTextField CampoSimple;
    private javax.swing.JTextField CampoSimpleE;
    private javax.swing.JCheckBox CheckBox1;
    private javax.swing.JCheckBox CheckBox1E;
    private javax.swing.JCheckBox CheckBox2;
    private javax.swing.JCheckBox CheckBox2E;
    private javax.swing.JCheckBox CheckBox3;
    private javax.swing.JCheckBox CheckBox3E;
    private javax.swing.JComboBox<String> ComboBoxItems;
    private javax.swing.JComboBox<String> ComboBoxItemsE;
    private javax.swing.JSpinner Contador;
    private javax.swing.JSpinner ContadorE;
    private javax.swing.JRadioButton RadioBoton1;
    private javax.swing.JRadioButton RadioBoton1E;
    private javax.swing.JRadioButton RadioBoton2;
    private javax.swing.JRadioButton RadioBoton2E;
    private javax.swing.JRadioButton RadioBoton3;
    private javax.swing.JRadioButton RadioBoton3E;
    private javax.swing.JLabel TextoCorreo;
    private javax.swing.JLabel TextoCorreoE;
    private javax.swing.JLabel tickVerde;
    // End of variables declaration//GEN-END:variables
}
