/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package elementosmixtos;

/**
 *
 * @author galog
 */
public class Elementos_Mixtos extends javax.swing.JFrame {

    /**
     * Creates new form Elementos_Mixtos
     */
    public Elementos_Mixtos() {
        initComponents();
        
        setTitle("GUI mixta");
        setResizable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RadioBoton1 = new javax.swing.JRadioButton();
        RadioBoton2 = new javax.swing.JRadioButton();
        RadioBoton3 = new javax.swing.JRadioButton();
        CheckBox1 = new javax.swing.JCheckBox();
        CheckBox2 = new javax.swing.JCheckBox();
        CheckBox3 = new javax.swing.JCheckBox();
        CampoSimple = new javax.swing.JTextField();
        CampoCorreo = new javax.swing.JTextField();
        TextoCorreo = new javax.swing.JLabel();
        ComboBoxItems = new javax.swing.JComboBox<>();
        BarraHorizontal = new javax.swing.JSlider();
        Contador = new javax.swing.JSpinner();
        BotonEstado = new javax.swing.JToggleButton();
        RadioBoton1E = new javax.swing.JRadioButton();
        RadioBoton2E = new javax.swing.JRadioButton();
        RadioBoton3E = new javax.swing.JRadioButton();
        CheckBox1E = new javax.swing.JCheckBox();
        CheckBox2E = new javax.swing.JCheckBox();
        CheckBox3E = new javax.swing.JCheckBox();
        CampoSimpleE = new javax.swing.JTextField();
        TextoCorreoE = new javax.swing.JLabel();
        CampoCorreoE = new javax.swing.JTextField();
        ContadorE = new javax.swing.JSpinner();
        ComboBoxItemsE = new javax.swing.JComboBox<>();
        BotonEstadoE = new javax.swing.JToggleButton();
        BarraHorizontalE = new javax.swing.JSlider();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GUI mixtsa");
        setResizable(false);

        RadioBoton1.setText("Opcion 1");

        RadioBoton2.setText("Opcion 2");

        RadioBoton3.setText("Opcion 3");

        CheckBox1.setText("Opcion 4");

        CheckBox2.setText("Opcion 5");

        CheckBox3.setText("Opcion 5");

        TextoCorreo.setText("Correo");

        ComboBoxItems.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        BotonEstado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elementosmixtos/b_off.png"))); // NOI18N

        RadioBoton1E.setText("Opcion 1");
        RadioBoton1E.setEnabled(false);

        RadioBoton2E.setText("Opcion 2");
        RadioBoton2E.setEnabled(false);

        RadioBoton3E.setText("Opcion 3");
        RadioBoton3E.setEnabled(false);
        RadioBoton3E.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioBoton3EActionPerformed(evt);
            }
        });

        CheckBox1E.setText("Opcion 4");
        CheckBox1E.setEnabled(false);

        CheckBox2E.setText("Opcion 5");
        CheckBox2E.setEnabled(false);

        CheckBox3E.setText("Opcion 6");
        CheckBox3E.setEnabled(false);

        CampoSimpleE.setEnabled(false);
        CampoSimpleE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoSimpleEActionPerformed(evt);
            }
        });

        TextoCorreoE.setText("Correo");
        TextoCorreoE.setEnabled(false);

        CampoCorreoE.setEnabled(false);

        ContadorE.setEnabled(false);

        ComboBoxItemsE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboBoxItemsE.setEnabled(false);

        BotonEstadoE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elementosmixtos/b_off.png"))); // NOI18N
        BotonEstadoE.setEnabled(false);

        BarraHorizontalE.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RadioBoton1)
                            .addComponent(RadioBoton2)
                            .addComponent(RadioBoton3)
                            .addComponent(TextoCorreo))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CampoCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(CheckBox2)
                                    .addComponent(CheckBox1)
                                    .addComponent(CheckBox3))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ComboBoxItems, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(CampoSimple, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(BarraHorizontal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Contador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(BotonEstado)
                                        .addGap(40, 40, 40))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(RadioBoton1E)
                                .addGap(18, 18, 18)
                                .addComponent(CheckBox1E))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(RadioBoton2E)
                                .addGap(18, 18, 18)
                                .addComponent(CheckBox2E))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(RadioBoton3E)
                                .addGap(18, 18, 18)
                                .addComponent(CheckBox3E)))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CampoSimpleE, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                                .addComponent(BarraHorizontalE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ComboBoxItemsE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ContadorE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(TextoCorreoE)
                        .addGap(56, 56, 56)
                        .addComponent(CampoCorreoE, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BotonEstadoE)
                        .addGap(42, 42, 42)))
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RadioBoton1)
                            .addComponent(CheckBox1)
                            .addComponent(CampoSimple, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BarraHorizontal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RadioBoton2)
                            .addComponent(CheckBox2)
                            .addComponent(Contador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(RadioBoton3)
                                    .addComponent(CheckBox3)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(ComboBoxItems, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(BotonEstado)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CampoCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextoCorreo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CampoSimpleE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RadioBoton1E)
                    .addComponent(CheckBox1E)
                    .addComponent(BarraHorizontalE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RadioBoton2E)
                    .addComponent(CheckBox2E)
                    .addComponent(ContadorE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RadioBoton3E)
                    .addComponent(CheckBox3E)
                    .addComponent(ComboBoxItemsE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextoCorreoE)
                    .addComponent(CampoCorreoE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonEstadoE))
                .addContainerGap(179, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CampoSimpleEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoSimpleEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoSimpleEActionPerformed

    private void RadioBoton3EActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioBoton3EActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioBoton3EActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Elementos_Mixtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Elementos_Mixtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Elementos_Mixtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Elementos_Mixtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Elementos_Mixtos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider BarraHorizontal;
    private javax.swing.JSlider BarraHorizontalE;
    private javax.swing.JToggleButton BotonEstado;
    private javax.swing.JToggleButton BotonEstadoE;
    private javax.swing.JTextField CampoCorreo;
    private javax.swing.JTextField CampoCorreoE;
    private javax.swing.JTextField CampoSimple;
    private javax.swing.JTextField CampoSimpleE;
    private javax.swing.JCheckBox CheckBox1;
    private javax.swing.JCheckBox CheckBox1E;
    private javax.swing.JCheckBox CheckBox2;
    private javax.swing.JCheckBox CheckBox2E;
    private javax.swing.JCheckBox CheckBox3;
    private javax.swing.JCheckBox CheckBox3E;
    private javax.swing.JComboBox<String> ComboBoxItems;
    private javax.swing.JComboBox<String> ComboBoxItemsE;
    private javax.swing.JSpinner Contador;
    private javax.swing.JSpinner ContadorE;
    private javax.swing.JRadioButton RadioBoton1;
    private javax.swing.JRadioButton RadioBoton1E;
    private javax.swing.JRadioButton RadioBoton2;
    private javax.swing.JRadioButton RadioBoton2E;
    private javax.swing.JRadioButton RadioBoton3;
    private javax.swing.JRadioButton RadioBoton3E;
    private javax.swing.JLabel TextoCorreo;
    private javax.swing.JLabel TextoCorreoE;
    // End of variables declaration//GEN-END:variables
}
