/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package elementosmixtos;

import java.awt.Color;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author galog
 */
public class Elementos_Mixtos extends javax.swing.JFrame {

    /**
     * Creates new form Elementos_Mixtos
     */
    public Elementos_Mixtos() {
        initComponents();
        
        setTitle("GUI mixta");
        setResizable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RadioBoton1 = new javax.swing.JRadioButton();
        RadioBoton2 = new javax.swing.JRadioButton();
        RadioBoton3 = new javax.swing.JRadioButton();
        CheckBox1 = new javax.swing.JCheckBox();
        CheckBox2 = new javax.swing.JCheckBox();
        CheckBox3 = new javax.swing.JCheckBox();
        CampoSimple = new javax.swing.JTextField();
        CampoCorreo = new javax.swing.JTextField();
        TextoCorreo = new javax.swing.JLabel();
        ComboBoxItems = new javax.swing.JComboBox<>();
        BarraHorizontal = new javax.swing.JSlider();
        Contador = new javax.swing.JSpinner();
        BotonEstado = new javax.swing.JToggleButton();
        RadioBoton1E = new javax.swing.JRadioButton();
        RadioBoton2E = new javax.swing.JRadioButton();
        RadioBoton3E = new javax.swing.JRadioButton();
        CheckBox1E = new javax.swing.JCheckBox();
        CheckBox2E = new javax.swing.JCheckBox();
        CheckBox3E = new javax.swing.JCheckBox();
        CampoSimpleE = new javax.swing.JTextField();
        TextoCorreoE = new javax.swing.JLabel();
        CampoCorreoE = new javax.swing.JTextField();
        ContadorE = new javax.swing.JSpinner();
        ComboBoxItemsE = new javax.swing.JComboBox<>();
        BotonEstadoE = new javax.swing.JToggleButton();
        BarraHorizontalE = new javax.swing.JSlider();
        BarraEstado = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GUI mixtsa");
        setResizable(false);

        RadioBoton1.setText("Opcion 1");
        RadioBoton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RadioBoton1MouseClicked(evt);
            }
        });

        RadioBoton2.setText("Opcion 2");
        RadioBoton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RadioBoton2MouseClicked(evt);
            }
        });

        RadioBoton3.setText("Opcion 3");
        RadioBoton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RadioBoton3MouseClicked(evt);
            }
        });

        CheckBox1.setText("Opcion 4");
        CheckBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CheckBox1MouseClicked(evt);
            }
        });

        CheckBox2.setText("Opcion 5");
        CheckBox2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CheckBox2MouseClicked(evt);
            }
        });

        CheckBox3.setText("Opcion 5");
        CheckBox3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CheckBox3MouseClicked(evt);
            }
        });

        CampoSimple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoSimpleActionPerformed(evt);
            }
        });
        CampoSimple.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CampoSimpleKeyTyped(evt);
            }
        });

        CampoCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoCorreoActionPerformed(evt);
            }
        });
        CampoCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CampoCorreoKeyTyped(evt);
            }
        });

        TextoCorreo.setText("Correo");

        ComboBoxItems.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboBoxItems.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ComboBoxItemsMouseClicked(evt);
            }
        });
        ComboBoxItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxItemsActionPerformed(evt);
            }
        });

        BarraHorizontal.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                BarraHorizontalMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                BarraHorizontalMouseMoved(evt);
            }
        });
        BarraHorizontal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BarraHorizontalMousePressed(evt);
            }
        });

        Contador.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                ContadorAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                ContadorAncestorMoved(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        Contador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ContadorMouseClicked(evt);
            }
        });

        BotonEstado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elementosmixtos/b_off.png"))); // NOI18N
        BotonEstado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonEstadoMouseClicked(evt);
            }
        });
        BotonEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEstadoActionPerformed(evt);
            }
        });

        RadioBoton1E.setText("Opcion 1");
        RadioBoton1E.setEnabled(false);

        RadioBoton2E.setText("Opcion 2");
        RadioBoton2E.setEnabled(false);

        RadioBoton3E.setText("Opcion 3");
        RadioBoton3E.setEnabled(false);
        RadioBoton3E.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioBoton3EActionPerformed(evt);
            }
        });

        CheckBox1E.setText("Opcion 4");
        CheckBox1E.setEnabled(false);

        CheckBox2E.setText("Opcion 5");
        CheckBox2E.setEnabled(false);

        CheckBox3E.setText("Opcion 6");
        CheckBox3E.setEnabled(false);

        CampoSimpleE.setEnabled(false);
        CampoSimpleE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoSimpleEActionPerformed(evt);
            }
        });

        TextoCorreoE.setText("Correo");
        TextoCorreoE.setEnabled(false);

        CampoCorreoE.setEnabled(false);

        ContadorE.setEnabled(false);

        ComboBoxItemsE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboBoxItemsE.setEnabled(false);

        BotonEstadoE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elementosmixtos/b_off.png"))); // NOI18N
        BotonEstadoE.setEnabled(false);

        BarraHorizontalE.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(RadioBoton3E)
                                .addGap(18, 18, 18)
                                .addComponent(CheckBox3E))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(RadioBoton1E)
                                .addGap(29, 29, 29)
                                .addComponent(CheckBox1E)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BotonEstadoE)
                                .addGap(83, 83, 83))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BarraHorizontalE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(RadioBoton2E)
                        .addGap(18, 18, 18)
                        .addComponent(CheckBox2E)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(TextoCorreoE)
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BarraEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CampoCorreoE, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RadioBoton1)
                            .addComponent(RadioBoton2)
                            .addComponent(RadioBoton3)
                            .addComponent(TextoCorreo))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CampoCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(CheckBox2)
                                    .addComponent(CheckBox1)
                                    .addComponent(CheckBox3))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(ComboBoxItems, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(Contador))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(BotonEstado)
                                        .addGap(52, 52, 52))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(CampoSimple, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(ContadorE, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(CampoSimpleE, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(ComboBoxItemsE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(BarraHorizontal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(29, 29, 29))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RadioBoton1)
                            .addComponent(CheckBox1)
                            .addComponent(CampoSimple, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BarraHorizontal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RadioBoton2)
                            .addComponent(CheckBox2)
                            .addComponent(Contador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(RadioBoton3)
                                    .addComponent(CheckBox3)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(ComboBoxItems, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(BotonEstado)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CampoCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextoCorreo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RadioBoton1E)
                            .addComponent(CheckBox1E))
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CampoSimpleE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BarraHorizontalE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RadioBoton2E)
                            .addComponent(CheckBox2E)
                            .addComponent(ContadorE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 91, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(RadioBoton3E)
                                    .addComponent(CheckBox3E)
                                    .addComponent(ComboBoxItemsE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(46, 46, 46))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(BotonEstadoE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CampoCorreoE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextoCorreoE))
                        .addGap(32, 32, 32)))
                .addComponent(BarraEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CampoSimpleEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoSimpleEActionPerformed
        //NO SIRVE ESTE EVENTO
        
    }//GEN-LAST:event_CampoSimpleEActionPerformed

    private void RadioBoton3EActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioBoton3EActionPerformed
        //NO SIRVE ESTE EVENTO
    }//GEN-LAST:event_RadioBoton3EActionPerformed

    private void BotonEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEstadoActionPerformed
        //NO SIRVE ESTE EVENTO
    }//GEN-LAST:event_BotonEstadoActionPerformed

    private void CampoSimpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoSimpleActionPerformed
        //NO SIRVE ESTE EVENTO
    }//GEN-LAST:event_CampoSimpleActionPerformed

    private void CampoSimpleKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CampoSimpleKeyTyped
        
        CampoSimpleE.setText(CampoSimple.getText());

    }//GEN-LAST:event_CampoSimpleKeyTyped

    private void CampoCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoCorreoActionPerformed
        //NO SIRVE ESTE EVENTO
    }//GEN-LAST:event_CampoCorreoActionPerformed

    private void CampoCorreoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CampoCorreoKeyTyped
        
        
        
//        CampoCorreo.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
//        @Override
//        public void insertUpdate(javax.swing.event.DocumentEvent e) {
//            actualizarTexto();
//        }
//
//        @Override
//        public void removeUpdate(javax.swing.event.DocumentEvent e) {
//            actualizarTexto();
//        }
//
//        @Override
//        public void changedUpdate(javax.swing.event.DocumentEvent e) {
//            actualizarTexto();
//        }
//
//        
//        private void actualizarTexto() {
//            CampoCorreo.setText(CampoCorreoE.getText());
//        }
//        });
        CampoCorreoE.setText(CampoCorreo.getText());
        if (!CampoCorreo.getText().contains("@") || !CampoCorreo.getText().contains(".")){
            CampoCorreo.setBorder(javax.swing.BorderFactory.createLineBorder(Color.RED));
            
        }
        
        if (CampoCorreo.getText().contains("@") && CampoCorreo.getText().contains(".")){
            CampoCorreo.setBorder(javax.swing.BorderFactory.createLineBorder(Color.GREEN));
            
       }
        
        
        
    }//GEN-LAST:event_CampoCorreoKeyTyped

    private void RadioBoton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RadioBoton1MouseClicked
        if (RadioBoton1.isSelected() == true){
            RadioBoton1E.setSelected(true);         
        }
        
        if (RadioBoton1.isSelected() == false){
            RadioBoton1E.setSelected(false);
        }
    }//GEN-LAST:event_RadioBoton1MouseClicked

    private void RadioBoton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RadioBoton2MouseClicked
        if (RadioBoton2.isSelected() == true){
            RadioBoton2E.setSelected(true);         
        }
        
        if (RadioBoton2.isSelected() == false){
            RadioBoton2E.setSelected(false);
        }
    }//GEN-LAST:event_RadioBoton2MouseClicked

    private void RadioBoton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RadioBoton3MouseClicked
        if (RadioBoton3.isSelected() == true){
            RadioBoton3E.setSelected(true);         
        }
        
        if (RadioBoton3.isSelected() == false){
            RadioBoton3E.setSelected(false);
        }
    }//GEN-LAST:event_RadioBoton3MouseClicked

    private void CheckBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CheckBox1MouseClicked
        if (CheckBox1.isSelected() == true){
            CheckBox1E.setSelected(true);         
        }
        
        if (CheckBox1.isSelected() == false){
            CheckBox1E.setSelected(false);
        }
    }//GEN-LAST:event_CheckBox1MouseClicked

    private void CheckBox2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CheckBox2MouseClicked
        if (CheckBox2.isSelected() == true){
            CheckBox2E.setSelected(true);         
        }
        
        if (CheckBox2.isSelected() == false){
            CheckBox2E.setSelected(false);
        }
    }//GEN-LAST:event_CheckBox2MouseClicked

    private void CheckBox3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CheckBox3MouseClicked
        if (CheckBox3.isSelected() == true){
            CheckBox3E.setSelected(true);         
        }
        
        if (CheckBox3.isSelected() == false){
            CheckBox3E.setSelected(false);
        }
    }//GEN-LAST:event_CheckBox3MouseClicked

    private void BotonEstadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonEstadoMouseClicked
        if (BotonEstado.isSelected() == true){
            BotonEstadoE.setSelected(true); 
        }
        
        if (BotonEstado.isSelected() == false){
            BotonEstadoE.setSelected(false);
        }
    }//GEN-LAST:event_BotonEstadoMouseClicked

    private void BarraHorizontalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraHorizontalMousePressed
        //NO SIRVE ESTE EVENTO
    }//GEN-LAST:event_BarraHorizontalMousePressed

    private void ComboBoxItemsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ComboBoxItemsMouseClicked

        //NO SIRVE ESTE EVENTO
    }//GEN-LAST:event_ComboBoxItemsMouseClicked

    private void ComboBoxItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxItemsActionPerformed
        ComboBoxItemsE.setSelectedIndex(ComboBoxItems.getSelectedIndex());
    }//GEN-LAST:event_ComboBoxItemsActionPerformed

    private void ContadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ContadorMouseClicked
//        Contador.addChangeListener(new ChangeListener(){
//            
//            
//           public void stateChanged (ChangeEvent e){
//               
//               int value = (int) Contador.getValue();
//               ContadorE.setValue(value);
//               
//           } 
//            
//        });
    }//GEN-LAST:event_ContadorMouseClicked

    private void BarraHorizontalMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraHorizontalMouseMoved
        //NO SIRVE ESTE EVENTO
    }//GEN-LAST:event_BarraHorizontalMouseMoved

    private void BarraHorizontalMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraHorizontalMouseDragged
        BarraHorizontalE.setValue(BarraHorizontal.getValue());
    }//GEN-LAST:event_BarraHorizontalMouseDragged

    private void ContadorAncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_ContadorAncestorMoved
        
        ContadorE.setValue(Contador.getValue());
        
    }//GEN-LAST:event_ContadorAncestorMoved

    private void ContadorAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_ContadorAncestorAdded
        ContadorE.setValue(Contador.getValue());
    }//GEN-LAST:event_ContadorAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Elementos_Mixtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Elementos_Mixtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Elementos_Mixtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Elementos_Mixtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Elementos_Mixtos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar BarraEstado;
    private javax.swing.JSlider BarraHorizontal;
    private javax.swing.JSlider BarraHorizontalE;
    private javax.swing.JToggleButton BotonEstado;
    private javax.swing.JToggleButton BotonEstadoE;
    private javax.swing.JTextField CampoCorreo;
    private javax.swing.JTextField CampoCorreoE;
    private javax.swing.JTextField CampoSimple;
    private javax.swing.JTextField CampoSimpleE;
    private javax.swing.JCheckBox CheckBox1;
    private javax.swing.JCheckBox CheckBox1E;
    private javax.swing.JCheckBox CheckBox2;
    private javax.swing.JCheckBox CheckBox2E;
    private javax.swing.JCheckBox CheckBox3;
    private javax.swing.JCheckBox CheckBox3E;
    private javax.swing.JComboBox<String> ComboBoxItems;
    private javax.swing.JComboBox<String> ComboBoxItemsE;
    private javax.swing.JSpinner Contador;
    private javax.swing.JSpinner ContadorE;
    private javax.swing.JRadioButton RadioBoton1;
    private javax.swing.JRadioButton RadioBoton1E;
    private javax.swing.JRadioButton RadioBoton2;
    private javax.swing.JRadioButton RadioBoton2E;
    private javax.swing.JRadioButton RadioBoton3;
    private javax.swing.JRadioButton RadioBoton3E;
    private javax.swing.JLabel TextoCorreo;
    private javax.swing.JLabel TextoCorreoE;
    // End of variables declaration//GEN-END:variables
}
